imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BaseBundle/Resources/config/services.yml" }
    - { resource: "@ColegioBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: colegio_defecto
        connections:
            # global
            global_defecto:
                driver:   pdo_mysql
                host:     "%db_host%"
                port:     "%db_port%"
                dbname:   "%db_global_defecto_name%"
                user:     "%db_global_defecto_user%"
                password: "%db_global_defecto_password%"
                charset:  UTF8
            global_persona:
                driver:   pdo_mysql
                host:     "%db_host%"
                port:     "%db_port%"
                dbname:   "%db_global_persona_name%"
                user:     "%db_global_persona_user%"
                password: "%db_global_persona_password%"
                charset:  UTF8
            # modulos
            colegio_defecto:
                driver:   pdo_mysql
                host:     "%db_host%"
                port:     "%db_port%"
                dbname:   "%db_colegio_defecto_name%"
                user:     "%db_colegio_defecto_user%"
                password: "%db_colegio_defecto_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: global_persona
        entity_managers:
            # global
            global_defecto:
                connection: global_defecto
                mappings:
                    BaseBundle: ~
            global_persona:
                connection: global_persona
                mappings:
                    BaseBundle: ~
            # modulos
            colegio_defecto:
                connection: colegio_defecto
                mappings:
                    ColegioBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
